import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Forquimia',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <head>
        <link rel='stylesheet' href='https://bootswatch.com/5/darkly/bootstrap.min.css' />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
